name: 'Destroy Test Environment'
description: 'Runs bbl destroy to tear down the entire test environment'

inputs:
  env_name:
    description: 'BBL environment name (state dir under the bbl-state repo)'
    required: true
  bbl_state_repo:
    description: 'Repo holding bbl state (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'Branch of the bbl state repo'
    required: false
    default: 'main'
  gcp_project_id:
    description: 'GCP project ID'
    required: true
  gcp_zone:
    description: 'GCP Zone'
    required: true
  gcp_region:
    description: 'GCP Region'
    required: true

outputs:
  success:
    description: 'Whether destroy succeeded (true if no-op or completed)'
    value: ${{ steps.destroy.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Checkout bbl state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}
        path: bbl-state

    - name: Setup tools (bbl)
      shell: bash
      run: |
        set -euo pipefail
        wget -O /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v9.0.36/bbl-v9.0.36_linux_amd64
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

    - name: Destroy environment
      id: destroy
      shell: bash
      run: |
        set -euo pipefail
        BBL_STATE_DIR="bbl-state/${{ inputs.env_name }}"
        
        echo "Checking for BBL state dir: $BBL_STATE_DIR"
        
        if [[ ! -d "$BBL_STATE_DIR" ]]; then
          echo "BBL state directory not found: $BBL_STATE_DIR"
          echo "Nothing to destroy"
          echo "success=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "State dir found. Proceeding with destroy..."
        
        KEY_FILE="$BBL_STATE_DIR/gcp-key.json"
        printf "%s" "${GCP_SERVICE_ACCOUNT_KEY}" > "$KEY_FILE"
        export BBL_GCP_SERVICE_ACCOUNT_KEY="$KEY_FILE"
        export BBL_GCP_PROJECT_ID="${{ inputs.gcp_project_id }}"
        export BBL_GCP_ZONE="${{ inputs.gcp_zone }}"
        export BBL_GCP_REGION="${{ inputs.gcp_region }}"
        export BBL_IAAS=gcp
        
        pushd "$BBL_STATE_DIR"
        echo "Running bbl destroy in $(pwd)"
        bbl destroy --no-confirm --state-dir .
        popd
        
        echo "Environment destroyed successfully"
        echo "success=true" >> $GITHUB_OUTPUT


    - name: Cleanup GCP key
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        BBL_STATE_DIR="bbl-state/${{ inputs.env_name }}"
        KEY_FILE="$BBL_STATE_DIR/gcp-key.json"
        if [[ -f "$KEY_FILE" ]]; then
          rm -f "$KEY_FILE"
          echo "GCP key file removed: $KEY_FILE"
        else
          echo "No GCP key file to cleanup"
        fi

    - name: Commit and push BBL state
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        STATE_REPO_DIR="bbl-state"
        
        pushd "$STATE_REPO_DIR"
        git config user.name "CF Buildpacks Eng Bot"
        git config user.email "test@test.com"
        
        if [[ -n "$(git status --porcelain)" ]]; then
          git add -A
          git commit -m "Clean up bbl state dir for ${{ inputs.env_name }} after destroy"
          git push origin ${{ inputs.bbl_state_branch }}
          echo "BBL state changes committed and pushed"
        else
          echo "No BBL state changes to commit."
        fi
        popd

