name: 'Setup Cloudflare DNS'
description: 'Configure DNS records for CF deployment based on BBL state'

inputs:
  env_name:
    description: 'BBL environment name'
    required: true
  bbl_state_repo:
    description: 'BBL state repo (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'BBL state branch'
    required: false
    default: main
  system_domain:
    description: 'System domain (e.g., sisle.org)'
    required: true

outputs:
  success:
    description: 'Whether DNS setup succeeded'
    value: ${{ steps.dns.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Checkout BBL state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        ssh-key: ${{ env.BBL_STATE_DEPLOY_KEY }}  
        path: bbl-state
        persist-credentials: false  

    - name: Install BBL, jq, and CF CLI
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update && sudo apt-get install -y jq
        
        wget -O /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v9.0.36/bbl-v9.0.36_linux_amd64
        chmod +x /tmp/bbl && sudo mv /tmp/bbl /usr/local/bin/bbl

        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update && sudo apt-get install -y cf8-cli
        
        echo "Tools installed: jq, bbl, cf-cli"

    - name: Setup Cloudflare DNS Records
      id: dns
      shell: bash
      run: |
        set -euo pipefail
        BBL_STATE_DIR="bbl-state/${{ inputs.env_name }}"
        DOMAIN="${{ inputs.system_domain }}"
        
        echo "BBL state dir: $BBL_STATE_DIR"
        
        if [[ ! -d "$BBL_STATE_DIR" ]]; then
          echo "Error: BBL state directory not found: $BBL_STATE_DIR"
          echo "Cannot set up DNS without state."
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        STATE_JSON="$BBL_STATE_DIR/bbl-state.json"
        if [[ ! -f "$STATE_JSON" ]]; then
          echo "Error: bbl-state.json not found in $BBL_STATE_DIR"
          echo "Run 'bbl up' first or check checkout."
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        if ! eval "$(bbl print-env --state-dir "$BBL_STATE_DIR")"; then
          echo "Error: Failed to load BBL env from $BBL_STATE_DIR"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "Parsing $STATE_JSON for IPs..."
        MAIN_LB_IP=$(jq -r '.bosh.load_balancer[0].ip // empty' "$STATE_JSON" | head -1)
        DIRECTOR_IP=$(jq -r '.bosh.director_address // empty' "$STATE_JSON")
        
        SSH_LB_IP=$(jq -r '.bosh.load_balancer[] | select(.name | contains("ssh")).ip // empty' "$STATE_JSON" | head -1)
        [[ -z "$SSH_LB_IP" ]] && SSH_LB_IP="${DIRECTOR_IP:-$MAIN_LB_IP}"
        
        TCP_LB_IP=$(jq -r '.bosh.load_balancer[] | select(.name | contains("tcp")).ip // empty' "$STATE_JSON" | head -1)
        [[ -z "$TCP_LB_IP" ]] && TCP_LB_IP="$MAIN_LB_IP"
        
        DOPPLER_LB_IP="${DIRECTOR_IP:-$MAIN_LB_IP}"
        LOGGREGATOR_LB_IP="$DOPPLER_LB_IP"  
        
        if [[ -z "$MAIN_LB_IP" ]]; then
          echo "Error: Could not extract main LB IP from $STATE_JSON. Check BBL state."
          echo "Sample content: $(head -c 200 "$STATE_JSON")..."
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "Extracted IPs from BBL state.json:"
        echo "- MAIN_LB_IP: $MAIN_LB_IP"
        echo "- SSH_LB_IP: $SSH_LB_IP"
        echo "- TCP_LB_IP: $TCP_LB_IP"
        echo "- DOPPLER_LB_IP: $DOPPLER_LB_IP"
        echo "- LOGGREGATOR_LB_IP: $LOGGREGATOR_LB_IP"
        
        ZONE_ID="${CLOUDFLARE_ZONE_ID:-}"
        API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
        
        if [[ -z "$ZONE_ID" || -z "$API_TOKEN" ]]; then
          echo "Error: Missing CLOUDFLARE_ZONE_ID or CLOUDFLARE_API_TOKEN env/secrets."
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        upsert_record() {
          local name="$1"  
          local ip="$2"
          local record_type="A"
          
          local api_name="$name"
          if [[ "$name" == "@" ]]; then
            api_name=""
          fi
          
          local existing_id=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=$record_type&name=${api_name}.${DOMAIN}" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" | jq -r '.result[0].id // empty')
          
          if [[ -n "$existing_id" ]]; then
            local success=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$existing_id" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{\"type\":\"$record_type\",\"name\":\"$api_name\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}" | jq -r '.success // empty')
            if [[ "$success" == "true" ]]; then
              echo "Updated $name.$DOMAIN -> $ip"
              return 0
            else
              echo "Update failed for $name.$DOMAIN: $(curl ... | jq -r '.errors[0].message // "Unknown error"')" 
              return 1
            fi
          else
            local success=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{\"type\":\"$record_type\",\"name\":\"$api_name\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}" | jq -r '.success // empty')
            if [[ "$success" == "true" ]]; then
              echo "Created $name.$DOMAIN -> $ip"
              return 0
            else
              echo "Create failed for $name.$DOMAIN: $(... | jq -r '.errors[0].message // "Unknown error"')"
              return 1
            fi
          fi
        }
        
        echo "Configuring DNS records for $DOMAIN (Zone ID: $ZONE_ID)..."
        local overall_success=true
        
        # doppler.sys
        if upsert_record "doppler.sys" "$DOPPLER_LB_IP"; then
          echo "✓ doppler.sys -> $DOPPLER_LB_IP"
        else
          echo "✗ Failed doppler.sys"
          overall_success=false
        fi
        
        # loggregator.sys
        if upsert_record "loggregator.sys" "$LOGGREGATOR_LB_IP"; then
          echo "✓ loggregator.sys -> $LOGGREGATOR_LB_IP"
        else
          echo "✗ Failed loggregator.sys"
          overall_success=false
        fi
        
        # * (wildcard for apps)
        if upsert_record "*" "$MAIN_LB_IP"; then
          echo "✓ *.${DOMAIN} -> $MAIN_LB_IP"
        else
          echo "✗ Failed wildcard"
          overall_success=false
        fi
        
        # sisle.org (apex)
        if upsert_record "@" "$MAIN_LB_IP"; then
          echo "✓ ${DOMAIN} (apex) -> $MAIN_LB_IP"
        else
          echo "✗ Failed apex"
          overall_success=false
        fi
        
        # ssh.sys
        if upsert_record "ssh.sys" "$SSH_LB_IP"; then
          echo "✓ ssh.sys -> $SSH_LB_IP"
        else
          echo "✗ Failed ssh.sys"
          overall_success=false
        fi
        
        # tcp.sys
        if upsert_record "tcp.sys" "$TCP_LB_IP"; then
          echo "✓ tcp.sys -> $TCP_LB_IP"
        else
          echo "✗ Failed tcp.sys"
          overall_success=false
        fi
        
        if [[ $overall_success == true ]]; then
          echo "::notice::All DNS records configured successfully for $DOMAIN"
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "::error::DNS setup partially failed. Check errors above."
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi


    - name: Cleanup on failure
      if: failure()
      shell: bash
      run: |
        set -euo pipefail
        echo "Cleanup: Removing temp state if partial failure"
        rm -rf bbl-state/*.json  
        echo "Cleanup complete"
