name: 'BBL Up'
description: 'Set up test environment using BBL with OIDC authentication'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  env_name:
    description: 'Environment name'
    required: true
  gcp_project_id:
    description: 'GCP Project ID'
    required: true
  gcp_zone:
    description: 'GCP Zone'
    required: true
  gcp_region:
    description: 'GCP Region'
    required: true
  lb_domain:
    description: 'Load balancer domain'
    required: true
  bbl_state_repo:
    description: 'Repo for BBL state (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'Branch for BBL state'
    required: false
    default: 'main'
  lb_cert:
    description: 'Load balancer certificate'
    required: true
  lb_key:
    description: 'Load balancer private key'
    required: true
  bbl_state_deploy_key:
    description: 'SSH deploy key for BBL state repo'
    required: true

outputs:
  success:
    description: 'Whether BBL up succeeded'
    value: ${{ steps.bbl-up.outputs.success }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        path: bbl-state
        ssh-key: ${{ inputs.bbl_state_deploy_key }}

    - name: Install tools
      shell: bash
      run: |
        wget -qO /tmp/bbl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v9.0.36/bbl-v9.0.36_linux_amd64
        wget -qO /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        wget -qO /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        
        chmod +x /tmp/bbl /tmp/bosh
        unzip -q /tmp/terraform.zip -d /tmp/
        sudo mv /tmp/{bbl,terraform,bosh} /usr/local/bin/

    - name: Run BBL
      id: bbl-up
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d)
        trap "rm -rf $TEMP_DIR" EXIT
        
        echo "${{ inputs.lb_cert }}" > "$TEMP_DIR/cert.pem"
        echo "${{ inputs.lb_key }}" > "$TEMP_DIR/key.pem"
        
        mkdir -p bbl-state/${{ inputs.env_name }}
        cd bbl-state/${{ inputs.env_name }}
        
        # Generate plan with dummy key (BBL requires it)
        openssl genrsa -out "$TEMP_DIR/dummy.pem" 2048 2>/dev/null
        cat > "$TEMP_DIR/dummy-key.json" <<EOF
        {
          "type": "service_account",
          "project_id": "${{ inputs.gcp_project_id }}",
          "private_key": "$(awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' $TEMP_DIR/dummy.pem)",
          "client_email": "dummy@${{ inputs.gcp_project_id }}.iam.gserviceaccount.com"
        }
        EOF
        
        bbl plan \
          --iaas gcp \
          --gcp-service-account-key "$TEMP_DIR/dummy-key.json" \
          --gcp-project-id "${{ inputs.gcp_project_id }}" \
          --gcp-zone "${{ inputs.gcp_zone }}" \
          --gcp-region "${{ inputs.gcp_region }}" \
          --lb-type cf \
          --lb-cert "$TEMP_DIR/cert.pem" \
          --lb-key "$TEMP_DIR/key.pem" \
          --lb-domain "${{ inputs.lb_domain }}"
        
        # Override Terraform to use OIDC
        echo 'provider "google" {}' > terraform/oidc_override.tf
        
        # Run with OIDC credentials
        bbl up --lb-domain "${{ inputs.lb_domain }}"
        
        echo "success=true" >> "$GITHUB_OUTPUT"

    - name: Save state
      shell: bash
      run: |
        cd bbl-state
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        
        cat >> .gitignore <<EOF
        **/*.pem
        **/*.key
        **/vars/*
        **/creds.yml
        **/*-key.json
        EOF
        
        git add -A
        git diff --staged --quiet || {
          git commit -m "Update BBL state: ${{ inputs.env_name }}"
          git push origin ${{ inputs.bbl_state_branch }}
        }
